# Generated by Django 5.0.6 on 2024-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friendlist',
            field=models.ManyToManyField(blank=True, to='user_profile.profile'),
        ),
    ]
